#! /bin/bash

#АВТОСТАРТ


#ВОРКСПЕЙСЫ
bspc monitor -d   1  2

#РАМКИ И ГАПСЫ
bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#ffffff"
bspc config active_border_color "#ffffff"
bspc config focused_border_color "#000000"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНАЫ
bspc config presel_feedback_color "#ffffff"

#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5

#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#ПРАВИЛА ОКОН
#bspc rule -a Firefox state=floating rectangle=1350x900+50+90 desktop='^1'

