#! /bin/bash

sxhkd &
numlockx &
nitrogen --restore &
polybar example &
xsetroot -cursor_name left_ptr &
firefox &
telegram-desktop &
picom &

bspc rule -a Firefox state=floating rectangle=1350x900+50+90 desktop='^1'
#bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+1450+90 desktop='^1'
bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6' 
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a dmenu rectangle=900x22+610+90
bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
bspc rule -a Inkscape desktop='^3'
bspc rule -a Blender desktop='^2'

bspc monitor -d              

bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#212a35"
bspc config active_border_color "#212a35"
bspc config focused_border_color "#fafafa"
bspc config presel_feedback_color "#212a35"

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
